language: node_js
node_js:
- stable
before_install:
- openssl aes-256-cbc -K $encrypted_649a32b406fd_key -iv $encrypted_649a32b406fd_iv -in deploy_key.enc -out deploy_key -d
script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "649a32b406fd"
  - COMMIT_AUTHOR_EMAIL: "gabriel@garox.org"
